# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/smart_warehouse
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=8080

# JWT
application.security.jwt.secret-key=8hY5J9mL2xQ7vT4kN8pR6sF1aD3gH7jK5mN2pL8vX4zQ9wE6rT1yU3iO7pA5sD9
application.security.jwt.expiration=86400000

